import { defaults, type State, type RecordItem } from "./domain";
export function seed(): State {
  const row = (
    id: string,
    source: "qbo" | "st",
    vendor: string,
    amount: number,
    date: string,
    reference = "",
    description = "Richmond service materials",
  ): RecordItem => ({
    id,
    source,
    vendor,
    amount,
    date,
    reference,
    description,
    currency: "USD",
    account: source === "qbo" ? "Visa · 4821" : "Richmond",
    cardUser:
      source === "qbo"
        ? {
            "Q-1041": "Alex Morgan",
            "Q-1042": "Chris Parker",
            "Q-1043": "Alex Morgan",
            "Q-1044": "Taylor Reed",
            "Q-1045": "Alex Morgan",
            "Q-1046": "Chris Parker",
            "Q-1047": "Chris Parker",
            "Q-1048": "Chris Parker",
            "Q-1049": "Taylor Reed",
            "Q-1050": "Alex Morgan",
            "Q-1052": "Taylor Reed",
            "Q-1053": "Taylor Reed",
            "Q-1054": "Chris Parker",
            "Q-1055": "Unassigned",
            "Q-1056": "Alex Morgan",
          }[id] || "Unassigned"
        : undefined,
    ownershipSource: source === "qbo" ? "Sample card assignment" : undefined,
    createdAt: date + "T12:00:00Z",
  });
  return {
    revision: 1,
    mode: "demo",
    config: structuredClone(defaults),
    lastSync: null,
    decisions: [],
    audit: [],
    coverage: {
      chargesFrom: "2026-09-01",
      posFrom: "2026-09-01",
      through: "2026-09-13",
    },
    vanStockTypeIds: ["demo-van-stock"],
    directory: {
      syncedAt: "2026-09-13T12:00:00Z",
      accounts: [
        "Alex Morgan",
        "Chris Parker",
        "Taylor Reed",
        "Unmapped card",
      ].map((name, i) => ({
        id: `demo-${81 + i}`,
        name: `Main CC: ${name}`,
        active: true,
        parentId: "demo-main",
      })),
      people: [
        ...["Alex Morgan", "Chris Parker", "Taylor Reed"].map((name, i) => ({
          id: `technician:demo-${i + 1}`,
          sourceId: `demo-${i + 1}`,
          name,
          kind: "technician" as const,
          active: true,
        })),
        {
          id: "employee:demo-office",
          sourceId: "demo-office",
          name: "Jamie Office",
          kind: "employee",
          active: true,
        },
      ],
      poTypes: [
        { id: "demo-job", name: "Job materials", active: true },
        { id: "demo-van-stock", name: "Van Stock", active: true },
      ],
    },
    rules: [
      {
        id: "alias-hd",
        type: "alias",
        pattern: "THE HOME DEPOT 4620",
        target: "Home Depot",
        maxCents: 0,
        approved: true,
        description: "Map Richmond store descriptor to Home Depot",
      },
      {
        id: "fuel",
        type: "no-po",
        pattern: "Shell",
        target: "",
        maxCents: 15000,
        approved: true,
        description: "Fleet fuel up to $150 per purchase",
      },
      {
        id: "suggest-1",
        type: "no-po",
        pattern: "Verizon",
        target: "",
        maxCents: 10000,
        approved: false,
        description:
          "Suggested recurring phone expense exemption. Approval required.",
      },
    ],
    records: [
      row(
        "Q-1041",
        "qbo",
        "THE HOME DEPOT 4620",
        48732,
        "2026-09-10",
        "PO-2041",
        "Plumbing repair · James River",
      ),
      row("PO-2041", "st", "Home Depot", 48732, "2026-09-09", "PO-2041"),
      row(
        "Q-1042",
        "qbo",
        "Ferguson",
        126480,
        "2026-09-10",
        "",
        "Water heater installation",
      ),
      row("PO-2042", "st", "Ferguson", 126480, "2026-09-09"),
      row(
        "Q-1043",
        "qbo",
        "Lowe’s",
        34218,
        "2026-09-04",
        "",
        "Deck repair · West End",
      ),
      row(
        "Q-1044",
        "qbo",
        "Grainger",
        68200,
        "2026-09-08",
        "PO-2044",
        "Safety equipment",
      ),
      row("PO-2044", "st", "Grainger", 62500, "2026-09-07", "PO-2044"),
      row(
        "Q-1045",
        "qbo",
        "Home Depot",
        72450,
        "2026-09-10",
        "",
        "Two service calls",
      ),
      row("PO-2045", "st", "Home Depot", 42000, "2026-09-08"),
      row("PO-2046", "st", "Home Depot", 30450, "2026-09-08"),
      row(
        "Q-1046",
        "qbo",
        "Sherwin Williams",
        18000,
        "2026-09-09",
        "",
        "Paint · first payment",
      ),
      row(
        "Q-1047",
        "qbo",
        "Sherwin Williams",
        14000,
        "2026-09-10",
        "",
        "Paint · balance",
      ),
      row("PO-2047", "st", "Sherwin Williams", 32000, "2026-09-08"),
      row(
        "Q-1048",
        "qbo",
        "Ferguson",
        -8900,
        "2026-09-09",
        "RT-201",
        "Returned fitting",
      ),
      row(
        "RT-201",
        "st",
        "Ferguson",
        -8900,
        "2026-09-08",
        "RT-201",
        "Vendor return credit",
      ),
      row("Q-1049", "qbo", "Ace Hardware", 11980, "2026-09-03", "PO-2049"),
      row("PO-2049", "st", "Ace Hardware", 11980, "2026-09-09", "PO-2049"),
      row("Q-1050", "qbo", "Shell", 7865, "2026-09-11", "", "Fleet fuel"),
      row(
        "PO-2051",
        "st",
        "Northern Tool",
        28999,
        "2026-09-01",
        "",
        "Replacement drill",
      ),
      row("Q-1052", "qbo", "Richmond Supply", 25400, "2026-09-09"),
      row("Q-1053", "qbo", "Richmond Supply", 25400, "2026-09-09"),
      row("PO-2052", "st", "Richmond Supply", 25400, "2026-09-08"),
      row(
        "Q-1054",
        "qbo",
        "Capital Electric",
        20000,
        "2026-09-08",
        "PO-2054",
        "Deposit on electrical supplies",
      ),
      row("PO-2054", "st", "Capital Electric", 60000, "2026-09-07", "PO-2054"),
      row(
        "Q-1055",
        "qbo",
        "Verizon",
        8500,
        "2026-09-05",
        "",
        "Monthly phone service",
      ),
      row(
        "Q-1056",
        "qbo",
        "Harbor Freight",
        5640,
        "2026-09-12",
        "",
        "Hand tools",
      ),
    ].map((r) =>
      r.source === "qbo"
        ? {
            ...r,
            accountId:
              (
                {
                  "Alex Morgan": "demo-81",
                  "Chris Parker": "demo-82",
                  "Taylor Reed": "demo-83",
                } as Record<string, string>
              )[r.cardUser || ""] || "demo-84",
            account: `Main CC: ${r.cardUser === "Unassigned" ? "Unmapped card" : r.cardUser}`,
          }
        : {
            ...r,
            poTypeId: ["PO-2044", "PO-2051"].includes(r.id)
              ? "demo-van-stock"
              : "demo-job",
            technicianId: (
              {
                "PO-2041": "demo-1",
                "PO-2042": "demo-2",
                "PO-2044": "demo-3",
                "PO-2045": "demo-1",
                "PO-2046": "demo-1",
                "PO-2047": "demo-2",
                "PO-2048": "demo-2",
                "PO-2049": "demo-3",
                "PO-2051": "demo-3",
                "PO-2052": "demo-3",
                "PO-2054": "demo-2",
              } as Record<string, string>
            )[r.id],
          },
    ),
  };
}
